#!/bin/bash
for ((x=0;x<100;x++))
do 
	#for D in 2
	#do
	#	for N in 5 10 50 100
	#	do
			echo "cat iris-data.txt | ./split.bash 50 ./id3.py > ./output/sa-${x}.txt"
	#	done
	#done
done  | xargs -L 1 -I CMD -P 64 bash -c CMD

