#!/bin/bash
for ((x=0;x<100;x++))
do 
	for D in 2
	do
		for N in 5 10 50 100
		do
			echo "./sa.py ${x} $D $N > ./output/sa-${x}-$D-$N.txt"
			echo "./greedy.py ${x} $D $N > ./output/greedy-${x}-$D-$N.txt"
		done
	done
done  | xargs -L 1 -I CMD -P 64 bash -c CMD

